version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: backend-saas-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_saas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Uncomment this section if you want to use local Redis instead of Upstash
  # redis:
  #   image: redis:latest
  #   container_name: backend-saas-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  postgres_data:
  # Uncomment this if you're using local Redis
  # redis_data: 